### ISSUE TITLE
Repetitive content on the Experience section of the blog

### ISSUE THREAD

**Issue by a4aditya** [atb00ker/atb00ker.github.io#15]
You mistakenly added the same content twice!! :p not a big issue but whatever...
![attached screenshot ](https://user-images.githubusercontent.com/39999719/71308588-7cd55600-2424-11ea-9de3-9d6074dafb70.png)

**Comment by atb00ker** [comment]
Thanks for bringing this up, I'll fix it in my next PR! :smile:

**Comment by atb00ker** [comment]
Thanks for reporting, fixed! :smile:
